version: 0.0
os: linux
files:
  - source: /frontend/build
    destination: /home/ec2-user/frontend/build   # Destination on the EC2 instance where frontend files should be copied

  -source: /backend
   destination: /home/ec2-user/backend

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300   # Set an appropriate timeout for your installation script
      runas: ec2-user  # Set the appropriate user to run the installation script
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300   # Set an appropriate timeout for your server start script
      runas: ec2-user  # Set the appropriate user to run the server start script
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user