version: 0.0
os: linux
files:
  - source: /frontend/build
    destination: /home/ec2-user/frontend/build   # Destination on the EC2 instance where frontend files should be copied

  - source: /backend
    destination: /home/ec2-user/backend  # Destination for backend files

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user
