version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install  # Install frontend dependencies

  pre_build:
    commands:
      - cd backend  # Change directory to the backend folder
      - npm install  # Install backend dependencies

  build:
    commands:
      - cd ../frontend  # Change back to the frontend folder
      - npm run build  # Build the frontend
      - cd ../backend  # Change back to the backend folder
      - npm run build  # Build the backend

artifacts:
  files:
    - backend/**/*  # Include backend build artifacts
    - frontend/build/**/*  # Include frontend build artifacts
