version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - cd backend  # Change directory to the backend folder
      - npm install  # Install backend dependencies

  build:
    commands:
      - cd ../frontend  # Change back to the frontend folder
      - npm install # Install frontend dependencies
      - npm run build  # Build the frontend

artifacts:
  files:
    - backend/**/*  # Include backend build artifacts
    - frontend/build/**/*  # Include frontend build artifacts

# Add the ArtifactsOverride section
ArtifactsOverride:
  files:
    - backend/**/*  # Include backend build artifacts
    - frontend/build/**/*  # Include frontend build artifacts